# Generated by Django 4.1.1 on 2022-09-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_auth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="myuser", name="credits",),
        migrations.RemoveField(model_name="myuser", name="is_active",),
        migrations.AddField(
            model_name="myuser",
            name="online",
            field=models.BooleanField(default=False),
        ),
    ]
