# Generated by Django 4.1.1 on 2022-09-21 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_auth", "0002_remove_myuser_credits_remove_myuser_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="myuser", name="online",),
    ]
